### ISSUE TITLE
Rename enums  to avoid clash with neopixel liv

### ISSUE THREAD

**Issue by pelikhan** [microsoft/ExpressivePixelsMakeCode#1]
https://github.com/microsoft/ExpressivePixelsMakeCode/blob/0ea6d7a3eefd77fe91827532bd5bc31578d3506f/EPXDisplay.ts#L4

Probably best to rename those enums to avoid name crashing with pet-beopixel

**Comment by GJSea** [comment]
@pelikhan now fixed
