### ISSUE TITLE
Readme needs update

### ISSUE THREAD

**Issue by abchatra** [microsoft/ExpressivePixelsMakeCode#3]
Couple of suggestions:
- It is asking users to load a different extension (https://github.com/microsoft/ExpressivePixels/tree/master/MakeCode).
- Documentation of the every block. When users right click on the block from allow listed extesion it takes to the readme served by our backend, something like this: https://makecode.microbit.org/pkg/microsoft/pxt-hacking-stem (See https://github.com/microsoft/pxt-hacking-stem Readme for reference)
-   Good to add where to buy the hardware as well

**Comment by GJSea** [comment]
Updated Readme
