### ISSUE TITLE
Remove unnecessary blocks

### ISSUE THREAD

**Issue by abchatra** [microsoft/ExpressivePixelsMakeCode#7]
There are some blocks which I am not sure what they do. 

![image](https://user-images.githubusercontent.com/6107272/100818529-31327700-33ff-11eb-8da5-063dfb6a4566.png)

Is it possible to remove the not necessary blocks and add documentation to all the remaining blocks in the readme?

**Comment by tballmsft** [comment]
Totally refactored to reduce number of APIs in extension to two.
